PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE clubs (   id            TEXT PRIMARY KEY,   name          TEXT NOT NULL,   timezone      TEXT NOT NULL DEFAULT 'Europe/London',   created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   archived_at   TEXT , slug TEXT, updated_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE people (   id              TEXT PRIMARY KEY,   auth_user_id    TEXT UNIQUE,            name            TEXT NOT NULL,   email           TEXT NOT NULL,   medical_flag    INTEGER NOT NULL DEFAULT 0,    rating          INTEGER,             notes_private   TEXT,          created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) , photo_url TEXT);
CREATE TABLE club_memberships (   id            TEXT PRIMARY KEY,   club_id       TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,   person_id     TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,   member_type   TEXT NOT NULL CHECK(member_type IN ('member','guest')),   status        TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('invited','active','suspended','left')),   joined_at     TEXT,   left_at       TEXT,   created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   UNIQUE(club_id, person_id) );
CREATE TABLE club_roles (   club_id       TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,   role_key      TEXT NOT NULL,        name          TEXT NOT NULL,   permissions_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL DEFAULT (datetime('now')),    PRIMARY KEY (club_id, role_key) );
CREATE TABLE club_member_roles (   club_id       TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,   person_id     TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,   role_key      TEXT NOT NULL,   created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   PRIMARY KEY (club_id, person_id, role_key),   FOREIGN KEY (club_id, role_key) REFERENCES club_roles(club_id, role_key) ON DELETE CASCADE );
CREATE TABLE invitations (   id            TEXT PRIMARY KEY,   club_id       TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,   email         TEXT NOT NULL,   name_hint     TEXT,   member_type   TEXT NOT NULL DEFAULT 'member' CHECK(member_type IN ('member','guest')),   role_key      TEXT,       group_id      TEXT,           token_hash    TEXT NOT NULL,      expires_at    TEXT,   accepted_at   TEXT,   created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) );
CREATE TABLE groups (   id            TEXT PRIMARY KEY,   club_id       TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,   name          TEXT NOT NULL,   kind          TEXT NOT NULL DEFAULT 'team' CHECK(kind IN ('team','committee','squad','other')),   description   TEXT,   created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   archived_at   TEXT );
CREATE TABLE group_members (   group_id      TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,   person_id     TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,   group_role    TEXT NOT NULL DEFAULT 'member' CHECK(group_role IN ('member','coach','captain','admin')),   added_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   PRIMARY KEY (group_id, person_id) );
CREATE TABLE event_series (   id              TEXT PRIMARY KEY,   club_id         TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,   group_id        TEXT REFERENCES groups(id) ON DELETE SET NULL,   title           TEXT NOT NULL,   description     TEXT,   location        TEXT,   weekday_mask    INTEGER NOT NULL DEFAULT 0,    start_time_local TEXT NOT NULL,        duration_min    INTEGER NOT NULL DEFAULT 60,   start_date      TEXT NOT NULL,        end_date        TEXT,           default_fee_cents INTEGER,         currency        TEXT NOT NULL DEFAULT 'GBP',   created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   archived_at     TEXT , visibility_days INTEGER NOT NULL DEFAULT 5);
CREATE TABLE event_rsvps (   event_id      TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,   person_id     TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,   response      TEXT NOT NULL CHECK(response IN ('yes','no','maybe')),   responded_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   note          TEXT, cancelled_late INTEGER NOT NULL DEFAULT 0,   PRIMARY KEY (event_id, person_id) );
CREATE TABLE event_attendance (   event_id      TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,   person_id     TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,   status        TEXT NOT NULL CHECK(status IN ('present','absent','late','excused')),   checked_in_at TEXT,   PRIMARY KEY (event_id, person_id) );
CREATE TABLE billing_plans (   id              TEXT PRIMARY KEY,   club_id         TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,   name            TEXT NOT NULL,              cadence         TEXT NOT NULL DEFAULT 'month' CHECK(cadence IN ('month')),   weekly_sessions_allowed INTEGER NOT NULL CHECK(weekly_sessions_allowed IN (1,2)),   price_cents     INTEGER NOT NULL,   currency        TEXT NOT NULL DEFAULT 'GBP',   stripe_price_id TEXT,                       active          INTEGER NOT NULL DEFAULT 1,   created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) , stripe_product_id TEXT, description TEXT, is_active INTEGER NOT NULL DEFAULT 1, sort_order INTEGER DEFAULT 0);
CREATE TABLE member_subscriptions (   id                    TEXT PRIMARY KEY,   club_id               TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,   person_id             TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,   plan_id               TEXT NOT NULL REFERENCES billing_plans(id) ON DELETE RESTRICT,   status                TEXT NOT NULL CHECK(status IN ('active','past_due','paused','cancelled')),   start_at              TEXT NOT NULL,   end_at                TEXT,   stripe_customer_id    TEXT,   stripe_subscription_id TEXT,   created_at            TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   UNIQUE(club_id, person_id, status)  );
CREATE TABLE subscription_usages (   subscription_id TEXT NOT NULL REFERENCES member_subscriptions(id) ON DELETE CASCADE,   event_id        TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,   used_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   PRIMARY KEY (subscription_id, event_id) );
CREATE TABLE payment_requests (   id            TEXT PRIMARY KEY,   club_id       TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,   event_id      TEXT REFERENCES events(id) ON DELETE SET NULL,   name          TEXT NOT NULL,              description   TEXT,   amount_cents  INTEGER NOT NULL,   currency      TEXT NOT NULL DEFAULT 'GBP',   due_at        TEXT,   status        TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','closed','cancelled')),   created_by_person_id TEXT REFERENCES people(id) ON DELETE SET NULL,   created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) );
CREATE TABLE payment_request_recipients (   payment_request_id TEXT NOT NULL REFERENCES payment_requests(id) ON DELETE CASCADE,   person_id          TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,   amount_cents       INTEGER,    status             TEXT NOT NULL DEFAULT 'due' CHECK(status IN ('due','paid','waived')),   PRIMARY KEY (payment_request_id, person_id) );
CREATE TABLE transactions (   id                TEXT PRIMARY KEY,   club_id           TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,   person_id         TEXT REFERENCES people(id) ON DELETE SET NULL,   event_id          TEXT REFERENCES events(id) ON DELETE SET NULL,   payment_request_id TEXT REFERENCES payment_requests(id) ON DELETE SET NULL,   source            TEXT NOT NULL CHECK(source IN ('stripe','cash','manual')),   type              TEXT NOT NULL CHECK(type IN ('charge','refund','adjustment')),   amount_cents      INTEGER NOT NULL,    currency          TEXT NOT NULL DEFAULT 'GBP',   status            TEXT NOT NULL CHECK(status IN ('pending','succeeded','failed','cancelled')),   stripe_payment_intent_id TEXT,   stripe_charge_id         TEXT,   stripe_refund_id         TEXT,    collected_by_person_id TEXT REFERENCES people(id) ON DELETE SET NULL,    created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   effective_at      TEXT );
CREATE TABLE refund_requests (   id                 TEXT PRIMARY KEY,   club_id            TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,   original_transaction_id TEXT NOT NULL REFERENCES transactions(id) ON DELETE RESTRICT,   requested_by_person_id  TEXT NOT NULL REFERENCES people(id) ON DELETE RESTRICT,   reason             TEXT,   status             TEXT NOT NULL DEFAULT 'requested' CHECK(status IN ('requested','approved','declined','processed')),   reviewed_by_person_id TEXT REFERENCES people(id) ON DELETE SET NULL,   reviewed_at        TEXT,   created_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) );
CREATE TABLE audit_log (   id            TEXT PRIMARY KEY,   club_id       TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,   actor_person_id TEXT REFERENCES people(id) ON DELETE SET NULL,   action        TEXT NOT NULL,           entity_type   TEXT NOT NULL,   entity_id     TEXT NOT NULL,   metadata_json TEXT NOT NULL DEFAULT '{}',   created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) );
CREATE TABLE event_teams ( id TEXT PRIMARY KEY, event_id TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE, name TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), UNIQUE(event_id, name) );
CREATE TABLE event_team_assignments (   event_id      TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,   person_id     TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,   team_id       TEXT REFERENCES event_teams(id) ON DELETE SET NULL,    activity      TEXT NOT NULL DEFAULT 'play'                CHECK(activity IN ('play','swim_sets','not_playing','other')),    position_code TEXT                CHECK(position_code IN ('F','W','C','B') OR position_code IS NULL),    notes         TEXT,    assigned_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   assigned_by_person_id TEXT REFERENCES people(id) ON DELETE SET NULL,    PRIMARY KEY (event_id, person_id) );
CREATE TABLE event_invitations (
  id            TEXT PRIMARY KEY,
  event_id      TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  person_id     TEXT REFERENCES people(id) ON DELETE CASCADE,
  group_id      TEXT REFERENCES groups(id) ON DELETE CASCADE,
  invited_by_person_id TEXT REFERENCES people(id) ON DELETE SET NULL,
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  -- Exactly one of person_id or group_id must be set
  CHECK ((person_id IS NOT NULL AND group_id IS NULL) OR (person_id IS NULL AND group_id IS NOT NULL))
);
CREATE TABLE series_invitations (
  id            TEXT PRIMARY KEY,
  series_id     TEXT NOT NULL REFERENCES event_series(id) ON DELETE CASCADE,
  person_id     TEXT REFERENCES people(id) ON DELETE CASCADE,
  group_id      TEXT REFERENCES groups(id) ON DELETE CASCADE,
  invited_by_person_id TEXT REFERENCES people(id) ON DELETE SET NULL,
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  -- Exactly one of person_id or group_id must be set
  CHECK ((person_id IS NOT NULL AND group_id IS NULL) OR (person_id IS NULL AND group_id IS NOT NULL))
);
CREATE TABLE IF NOT EXISTS "events" (   id TEXT PRIMARY KEY,   club_id TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,   group_id TEXT REFERENCES groups(id) ON DELETE SET NULL,   series_id TEXT REFERENCES event_series(id) ON DELETE SET NULL,    kind TEXT NOT NULL DEFAULT 'session'     CHECK(kind IN ('session','tournament','social','ladies','training','other')),    title TEXT NOT NULL,   description TEXT,   location TEXT,   starts_at_utc TEXT NOT NULL,   ends_at_utc TEXT NOT NULL,   timezone TEXT NOT NULL DEFAULT 'Europe/London',   capacity INTEGER,   status TEXT NOT NULL DEFAULT 'scheduled'     CHECK(status IN ('scheduled','cancelled','completed')),   payment_mode TEXT NOT NULL DEFAULT 'included'     CHECK(payment_mode IN ('included','one_off','free')),   fee_cents INTEGER,   currency TEXT NOT NULL DEFAULT 'GBP',   created_by_person_id TEXT REFERENCES people(id) ON DELETE SET NULL,   created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   visible_from TEXT , google_event_id TEXT, google_last_synced_at TEXT);
CREATE TABLE external_events (   id              TEXT PRIMARY KEY,                   source          TEXT NOT NULL,                    source_event_id TEXT NOT NULL,      title           TEXT NOT NULL,   description     TEXT,   location        TEXT,   starts_at_utc   TEXT NOT NULL,   ends_at_utc     TEXT,   timezone        TEXT NOT NULL DEFAULT 'Europe/London',   url             TEXT,   status          TEXT NOT NULL DEFAULT 'active'    CHECK(status IN ('active','cancelled','tentative')),   raw_json        TEXT,                             last_seen_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), visibility TEXT NOT NULL DEFAULT 'public' CHECK(visibility IN ('public','admin_only','coach_only')), origin TEXT NOT NULL DEFAULT 'import' CHECK(origin IN ('import','manual')), created_by_person_id TEXT REFERENCES people(id) ON DELETE SET NULL, updated_by_person_id TEXT REFERENCES people(id) ON DELETE SET NULL,   UNIQUE(source, source_event_id) );
CREATE TABLE external_event_links (   id                TEXT PRIMARY KEY,   club_id           TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,   external_event_id TEXT NOT NULL REFERENCES external_events(id) ON DELETE CASCADE,    decision          TEXT NOT NULL DEFAULT 'undecided'                     CHECK(decision IN ('undecided','promoted','ignored')),   event_id          TEXT REFERENCES events(id) ON DELETE SET NULL,    group_id          TEXT REFERENCES groups(id) ON DELETE SET NULL,   notes             TEXT,    decided_by_person_id TEXT REFERENCES people(id) ON DELETE SET NULL,   decided_at        TEXT,   created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),    UNIQUE(club_id, external_event_id) );
CREATE TABLE awards (   id          TEXT PRIMARY KEY,      name        TEXT NOT NULL,   description TEXT NOT NULL,   icon        TEXT,                   created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) );
CREATE TABLE user_awards (   id          TEXT PRIMARY KEY,      user_id     TEXT NOT NULL,             award_id    TEXT NOT NULL REFERENCES awards(id) ON DELETE CASCADE,   granted_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),   meta_json   TEXT,   UNIQUE(user_id, award_id) );
CREATE INDEX idx_people_email ON people(email);
CREATE INDEX idx_people_auth_user_id ON people(auth_user_id);
CREATE INDEX idx_club_memberships_club_status ON club_memberships(club_id, status);
CREATE INDEX idx_club_memberships_club_person ON club_memberships(club_id, person_id);
CREATE INDEX idx_club_member_roles_person ON club_member_roles(person_id);
CREATE INDEX idx_invitations_club_email ON invitations(club_id, email);
CREATE INDEX idx_groups_club ON groups(club_id);
CREATE INDEX idx_group_members_person ON group_members(person_id);
CREATE INDEX idx_event_series_club_group ON event_series(club_id, group_id);
CREATE INDEX idx_event_rsvps_event_response ON event_rsvps(event_id, response);
CREATE INDEX idx_event_rsvps_person ON event_rsvps(person_id);
CREATE INDEX idx_event_attendance_event_status ON event_attendance(event_id, status);
CREATE INDEX idx_billing_plans_club_active ON billing_plans(club_id, active);
CREATE INDEX idx_member_subscriptions_club_person ON member_subscriptions(club_id, person_id);
CREATE INDEX idx_member_subscriptions_stripe_sub ON member_subscriptions(stripe_subscription_id);
CREATE INDEX idx_subscription_usages_event ON subscription_usages(event_id);
CREATE INDEX idx_payment_requests_club_event ON payment_requests(club_id, event_id);
CREATE INDEX idx_payment_requests_club_status ON payment_requests(club_id, status);
CREATE INDEX idx_payment_request_recipients_person ON payment_request_recipients(person_id);
CREATE INDEX idx_transactions_club_created ON transactions(club_id, created_at);
CREATE INDEX idx_transactions_person_created ON transactions(person_id, created_at);
CREATE INDEX idx_transactions_event ON transactions(event_id);
CREATE UNIQUE INDEX uq_transactions_stripe_pi ON transactions(stripe_payment_intent_id) WHERE stripe_payment_intent_id IS NOT NULL;
CREATE INDEX idx_refund_requests_club_status ON refund_requests(club_id, status);
CREATE INDEX idx_audit_log_club_created ON audit_log(club_id, created_at);
CREATE INDEX idx_event_teams_event ON event_teams(event_id);
CREATE INDEX idx_event_team_assignments_event_team ON event_team_assignments(event_id, team_id);
CREATE INDEX idx_event_team_assignments_event_activity ON event_team_assignments(event_id, activity);
CREATE UNIQUE INDEX uq_event_invitations_person ON event_invitations(event_id, person_id) WHERE person_id IS NOT NULL;
CREATE UNIQUE INDEX uq_event_invitations_group ON event_invitations(event_id, group_id) WHERE group_id IS NOT NULL;
CREATE INDEX idx_event_invitations_event ON event_invitations(event_id);
CREATE INDEX idx_event_invitations_person ON event_invitations(person_id) WHERE person_id IS NOT NULL;
CREATE UNIQUE INDEX uq_series_invitations_person ON series_invitations(series_id, person_id) WHERE person_id IS NOT NULL;
CREATE UNIQUE INDEX uq_series_invitations_group ON series_invitations(series_id, group_id) WHERE group_id IS NOT NULL;
CREATE INDEX idx_series_invitations_series ON series_invitations(series_id);
CREATE INDEX idx_events_club_starts ON events(club_id, starts_at_utc);
CREATE INDEX idx_events_group_starts ON events(group_id, starts_at_utc);
CREATE INDEX idx_events_series_starts ON events(series_id, starts_at_utc);
CREATE INDEX idx_events_club_status_starts ON events(club_id, status, starts_at_utc);
CREATE INDEX idx_external_events_source_starts   ON external_events(source, starts_at_utc);
CREATE INDEX idx_external_events_last_seen   ON external_events(last_seen_at);
CREATE INDEX idx_external_event_links_club_decision   ON external_event_links(club_id, decision);
CREATE INDEX idx_external_event_links_event   ON external_event_links(event_id);
CREATE INDEX idx_external_events_origin_visibility_starts ON external_events(origin, visibility, starts_at_utc);
